spring.application.name=demo

spring.data.mongodb.uri=mongodb+srv://saivenkatkallepalli_db_user:1hgmY4Q0jIGCVN19@cluster0.rkpjkya.mongodb.net/chat_db?appName=Cluster0

server.port=8000

jwt.secret=your-very-secret-key-that-must-be-at-least-32-bytes-long!